### ISSUE TITLE
Slows Homebridge down, leading to "no response" errors

### ISSUE THREAD

**Issue by beatpaul** [skrollme/homebridge-eveatmo#19] opened 2018-11-25 13:41 UTC
Hi!

If there is no server connection to netatmo servers (what happens lately a lot) the plugin slows homebridge down so u can't us it any more
Same issue as 
https://github.com/planetk/homebridge-netatmo/issues/73 

Is there a workaround?

thx in advance

**Comment by skrollme** [comment] 2018-11-27 07:46
Are you on the latest version of homebridge-eveatmo, @beatpaul ? For me there are currently no problems, even the history works well.

**Comment by Acemach1ne** [comment] 2018-11-27 14:53
Same here. Latest version installed.

**Comment by skrollme** [comment] 2018-11-27 15:09
It is difficult to debug this at the moment, because this does not occurs in my setup (eveatmo with some other plugins on raspberryPi), but will look into this: May reducing the connection-timeout could be an option.

**Comment by beatpaul** [comment] 2018-11-27 18:41
Hi!
Yes i used the latest Version, running on a mac mini with several other plugins like homebridge-hue e.g.

**Comment by Acemach1ne** [comment] 2018-11-27 20:13
Homebridge status:
https://www.dropbox.com/s/uyctxeq3fcx0xbb/Foto%2027.11.18%2C%2021%2011%2031.png?dl=0

**Comment by skrollme** [comment] 2018-11-29 14:38
@Acemach1ne I also get a batch of "invalid access token" messages once. After a restart everything was fine again. Does this work for you as a temporary fix if you are still facing the problems? Or did the problems disappear by themselves?

**Comment by Acemach1ne** [comment] 2018-11-29 18:48
@skrollme 
It was related to the downtime of Netatmo. After the server ran again, the problem fixed themselve. A restart of Homebridge didnt fixed the problem.

**Comment by cschildhorn** [comment] 2018-12-02 23:56
I see these errors after a few hours last days:

[12/3/2018, 12:33:04 AM] [eveatmo platform] WARN - Netatmo: Error: getStationsDataError error: Access token expired

All Sensor do not respond and the error makes all other plugins unresponsive as well. 

Restarting homebridge solves issue but the token is not renewed without the reboot.

**Comment by skrollme** [comment] 2018-12-04 20:20
I had still no luck with debugging but in the last few days I had not a single "token expired" error in my logs. My polling interval is 540s (9min) by the way. Every now and then I got an "internal server error" from the netamo API but even then I have no freezes in the Home.app.

I will continue to look into this but at the moment if have no real clues how to start with this. Suggestions are welcome.

**Comment by skrollme** [comment] 2019-01-21 07:20
Any new information on this, @cschildhorn ? Did it happen again? Please also take a look at this issue and my answer there: https://github.com/skrollme/homebridge-eveatmo/issues/25

I will close this soo because it seems that we can make no progress here.

**Comment by cschildhorn** [comment] 2019-01-21 19:34
Hi,

I still have sometimes the "token expired" error in my logs. Homebridge is freezing and no new data in the eve app for example. Restarting service always fixes this. The last entires in the homebridge log are a few of this errors before the freeze.

**Comment by skrollme** [comment] 2019-01-22 12:35
Interesting. I took a look at my homebridge log from the last weeks and I see that every now and then the following error occurred once, followed by successful data-request. 
`[eveatmo] WARN - Netatmo: Error: getStationsDataError error: Access token expired`

So the token gets renewed automatically (as designed) and the plugin continues it's work. At the moment I have no idea how to debug this. Maybe it is a good start for you to learn nodeJS (if you are not already a pro) and start debugging ;)

**Comment by schroot72** [comment] 2019-04-18 07:32
I have The same problem. Maybe the token should be refreshed ? https://dev.netatmo.com/en-US/resources/technical/guides/authentication/refreshingatoken

**Comment by skrollme** [comment] 2019-04-25 16:01
Because I forked the plugin from the base Netatmo-plugin I never really looked/overhauled into the base-logic which fetches the data from the API.
I will take a look at this soon.

**Comment by skrollme** [comment] 2019-04-26 18:06
I checked the used Netatmo-library:
On [this line](https://github.com/karbassi/netatmo/blob/master/netatmo.js#L123) the refresh is automatically set up with a timer, **if** the _expires_in_-value is set in the first auth-response. I manually did an auth-request to check this, and _expires_in_ **is set**!

The value for _expires_in_ is _10800_, which equals to 3 hours. So if the refresh would not work, the plugin would stop after 3 hours. Although I did not have the problems you describe - even in long and continously running situations - I trust your words and problem descriptions ;) 

I plan to add an config-option to trigger a forced re-authenticate in the Netatmo-library. Maybe I find some time for this on this weekend. I will let you know if this is done.

**Comment by skrollme** [comment] 2019-05-01 08:58
**Update:** 
So far I did not find a working solution to regularly trigger a reauthenticate without breaking everything else. The underlying netatmo-library fires events in this case which break things else or re-calls callbacks which should not have been called a second time. 

Also I would not consider myself a NodeJS pro - only "learned" this a bit for my personal homebridge projects - and so I plan to stop investigating this one here. If anyone has the knowledge and spare time, I would appreciate further research and maybe a PullRequest, but I'm sorry to say that my efforts on this will stop here. 

I will keep the issue open for a while.

**Comment by vidalpascual** [comment] 2019-08-27 08:11
Any news about this? I have the same issue described above with the same errors. It seems that Netatmo have changed something in their servers.

**Comment by skrollme** [comment] 2019-08-27 18:02
I just looked into my homebridge-log and there was no single eveatmo-error in the last 3 days. So it does not seem to be a general issue. My polling-interval is 1 call every 9min at the moment

**Closed** 2019-11-03 20:24 UTC
Labels: bug
