### ISSUE TITLE
Illegal Characteristic Supplied on Homebridge 1.3.0 Beta

### ISSUE THREAD

**Issue by Marfre888** [skrollme/homebridge-eveatmo#56] opened 2021-02-16 10:13 UTC
**Describe the bug**
As Homebridge log states, firmware characteristic is supplied as a number not string.

**Version you use**
- homebridge version 1.3.0-Beta
- node version 14.15.5
- plugin version 0.6.2

**To Reproduce**
Upon restarting Homebridge with 1.3.0Beta

![error](https://user-images.githubusercontent.com/63603736/108048838-cb41ad00-7047-11eb-81e9-adc7271029b2.PNG)

![battery](https://user-images.githubusercontent.com/63603736/108051351-14473080-704b-11eb-8fc0-074ad0e18bd2.PNG)

**Comment by mrmaximas** [comment] 2021-02-17 15:20
same  issue

**Comment by Marfre888** [comment] 2021-02-18 11:35
![evatmo](https://user-images.githubusercontent.com/63603736/108351432-cfa3cc80-71e5-11eb-8e84-452bfde79c50.PNG)

**Comment by misanthrophy** [comment] 2021-02-20 08:44
Same here too.

**Comment by DJay-X** [comment] 2021-02-20 11:43
Public of Homebridge v1.3.0

[20.2.2021, 11:45:42] [homebridge-eveatmo] This plugin generated a warning from the characteristic 'S2W2': SET handler returned write response value, though the characteristic doesn't support write response! See https://git.io/JtMGR for more info.
[Zuhause (Wohnzimmer) Balkon@Zuhause (Wohnzimmer) Balkon History@S2W1] SET handler returned write response value, though the characteristic doesn't support write response!
[20.2.2021, 11:45:42] [homebridge-eveatmo] This plugin generated a warning from the characteristic 'S2W1': SET handler returned write response value, though the characteristic doesn't support write response! See https://git.io/JtMGR for more info.

**Comment by skrollme** [comment] 2021-02-20 15:33
Looks like I have to update to 1.3 to check and fix this... :D

**Comment by skrollme** [comment] 2021-02-20 16:22
I fixed the firmware- and hopefully the battery-characteristics warning although the later does not showed up in my logs.
When do S2W1 and S2W2-warnings show up in your logs @DJay-X ? On Startup, every now and then, while fetching the data (via EVE.app)? I haven't seen them so far either.

**Comment by misanthrophy** [comment] 2021-02-20 21:21
@skrollme when can we expect the update and test if there are any further issues? :)

**Comment by skrollme** [comment] 2021-02-21 09:32
I want to wait for the reply of DJay concerning his problem. As far as I understand the plugin works as it did before, there are just some warning log entries now. So no need to hurry

**Comment by mrmaximas** [comment] 2021-02-21 09:53
after update HB to 1.3.0 release no warnings appear

**Comment by DJay-X** [comment] 2021-02-21 11:06
> I want to wait for the reply of DJay concerning his problem. As far as I understand the plugin works as it did before, there are just some warning log entries now. So no need to hurry

Thanks @skrollme I waited yesterday and today but was not able to reproduce the log entry for whatever reason. So we are on the same page, nothing critical I guess.  Thanks again.

**Comment by skrollme** [comment] 2021-02-21 12:26
update 0.6.3 was released an hour ago and is already running on my setup. So far most of the warning are gone. But now the S2W1 and S2W2-warnings showed up in my logs too, @DJay-X :D 
It will take a look at it soon and publish another release when I found a fix for this.

**Comment by misanthrophy** [comment] 2021-02-21 13:56
> update 0.6.3 was released an hour ago and is already running on my setup. So far most of the warning are gone. But now the S2W1 and S2W2-warnings showed up in my logs too, @DJay-X :D
> It will take a look at it soon and publish another release when I found a fix for this.

Same here, I got the warnings now too ^^

**Comment by skrollme** [comment] 2021-02-21 13:59
Looks like the _S2W1 and S2W2-warnings_ come from the underlying fakegato-plugin, which is used to handle the history-functionality. I updated _homebridge-eveatmo_ to the latest version if _fakegato_ (0.6.1) and just published another release 0.6.4. Because the _S2W*-warnings_ come not from the code of _homebridge-eveatmo_, it looks like there is nothing more I can do about it.

**Closed by skrollme** 2021-02-21 13:59 UTC
Labels: bug
