### ISSUE TITLE
Homekit crash

### ISSUE THREAD

**Issue by damianfm** [skrollme/homebridge-eveatmo#45] opened 2020-10-14 10:40 UTC
Hi!

I have homebridge-eveatmo plugin and homebridge 1.1.2 and it was running ok until i upgraded to 1.1.6. In hombrebridge it's ok, i see temperature, humidity, etc... but it makes a crash in homekit-homebridge connection because all other elements show as disconnected when i have homebridge-eveatmo "online", if i delete this plugin, all elements show online again. I've tried multiple configurations, reinstall homebridge, reinstall plugins and always, when i install homebridge-eveatmo plugin, it crash

**Comment by gioz73** [comment] 2020-10-30 05:02
Hi, I have the same issue. 
Homebridge v1.1.6
Node v14.15.0
Npm V 6.14.8

**Comment by skrollme** [comment] 2020-11-01 13:24
I was still on _homebridge@1.1.0_ but I just updated to v1.1.6. Everything works fine in my setup (_homebridge_ on a _node:10-alpine_-image inside docker on raspberryPi, 6 plugins including _homebridge-eveatmo@0.5.0_)

So it does not seem to be a general issue. Please provide more details on the problem (error messages, logs, ..) or I will close this issue soon.

**Comment by gioz73** [comment] 2020-11-01 17:58
I have reinstalled this homebridge three times https://github.com/homebridge/homebridge-raspbian-image 
and I've always had the same problem.

Inviato da iPhone

**Comment by skrollme** [comment] 2020-11-01 19:22
As I wrote before: Please provide more information on what happens exactly. Error messages, logs, ...  "The same problem" or "it crashes" does not help.

**Comment by gioz73** [comment] 2020-11-01 20:43
Inviato da iPhone

**Comment by damianfm** [comment] 2020-11-03 23:44
There are not homebridge errors (debug mode), no more info shows in logs, in homebridge netatmo temp, humidity, etc.. ok but, in homekit, all homebridge accesories are "not responding" when i install eveatmo plugin and restart homebridge. I have 12 plugins installed and only crash with eveatmo, sorry, i can't give you error logs because there aren't any errors in logs

**Comment by Blog404DE** [comment] 2020-11-06 14:50
### System Information
System: Rasbian (Raspbian GNU/Linux Buster (10)) / Raspberry 4
NodeJS: v12.19.0
NPM: 6.14.8
Homebridge: v1.1.6

Installed Homebrige-Plugins:
├── homebridge-config-ui-x@4.31.0
├── homebridge-eveatmo@0.5.0
├── homebridge-hue@0.11.77

### Problem-Description

I could confirm this bug, too. I've installed homebridge complete from scratch with only three plugins and everything was working again ... but only for some hour. After some test-restarts of homebridge every accessory was "not responding". I've checked the normal log and after it the debug log and there was no explicit error message or warning. Homebridge itself and homebridge-config-ui-x still worked without any problem. Only "Home" on iOS, iPadOS and macOS seems to get no connection to Homebridge. You could even see the pairing between the client and homebridge.

```HAP-NodeJS:EventedHTTPServer [::ffff:192.168.0.xx] New connection from client at interface eth0 +33s
HAP-NodeJS:EventedHTTPServer [::ffff:192.168.0.xx] HTTP server listening on port 33621 +1ms
HAP-NodeJS:EventedHTTPServer [::ffff:192.168.0.xx] HTTP request: /pair-verify +4ms
HAP-NodeJS:HAPServer [0E:83:1E:E1:xx:xx] HAP Request: POST /pair-verify +33s
HAP-NodeJS:HAPServer [0E:83:1E:E1:xx:xx] Pair verify step 1/2 +1ms
HAP-NodeJS:EventedHTTPServer [::ffff:192.168.0.xx] HTTP Response is finished +80ms
HAP-NodeJS:EventedHTTPServer [::ffff:192.168.0xx50] HTTP request: /pair-verify +23ms
HAP-NodeJS:HAPServer [0E:83:1E:E1:xx:xx] HAP Request: POST /pair-verify +103ms
HAP-NodeJS:HAPServer [0E:83:1E:E1:xx:xx] Pair verify step 2/2 +0ms
HAP-NodeJS:HAPServer [0E:83:1E:E1:xx:xx] Client 3FEDxxxx-xxxx-xxxx-xxxx-xxxxA8C2505 verification complete +40ms
HAP-NodeJS:EventedHTTPServer [::ffff:192.168.0.xx] HTTP Response is finished +43ms
HAP-NodeJS:EventedHTTPServer [::ffff:192.168.0.xx] HTTP request: /accessories +8ms
HAP-NodeJS:HAPServer [0E:83:1E:E1:xx:xx] HAP Request: GET /accessories +10ms
HAP-NodeJS:EventedHTTPServer [::ffff:192.168.0.xx] HTTP Response is finished +21ms
```

It's really curios, because the first hours and restarts everything was working without any problem - and I know, tracking down this bug with nearly no error-message/-code will be really heavy.

### Workaround

The only workaround i've found was removing eveatmo from homebridge :-/

**Comment by skrollme** [comment] 2020-11-11 19:42
I'm still completely clueless how this come from and how to reproduce this. A few node versions ago I had similar problems. It worked for a short time after restart and then it stopped. This behavior was caused by connections which could not kept open  for long enough. 
Currently I'm using node v10.23.0 - the LTS - , and honestly I do not see a reason why I should update it because it works and it is only needed inside this single docker-container.

**Comment by Blog404DE** [comment] 2020-11-12 16:42
I really understand it - it's really difficult to track it down. 

I've tested it with Node v10.23.0 (as you) and v12.19.0. Homebridge was testet with Version 1.3.0-beta.22, 1.2.3 and 1.1.6 (latest Version).  Eveatmo had the version 0.5.0 and it was installed on the Raspbian Image (Buster).

For now, I'm using the nativ HomeKit support from my Netatmo Station - even if the "Eve"-extension is not supported by Netatmo.

/Off-Topic:
The reason for updating nodejs on my side was homebridge-hue. The developer of this plugin told his user to update nodejs 14.x, because he wouldn't test homebridge-hue on older nodejs versions. Soon or later, more developer will make the same step.

**Comment by Dobryash** [comment] 2020-11-26 19:22
I think this topic is related to https://github.com/skrollme/homebridge-eveatmo/issues/47
If I uninstall the plugin, I can safely connect the homebridge to the home kit, but as soon as I add the palgin, all devices stop responding through it. With the yt plugin installed, the homebridge is connected to the home kit.
ios 14.2.1
Hoobs 3.2.10
Node Version 12.19.0

**Comment by depaolam** [comment] 2021-07-08 13:48
Not sure if this helps, but I had this problem when I was running node.js 14.17.x. I just upgraded to 16.x, reinstalled this plugin and it's totally happy now.

**Closed** 2022-04-17 12:24 UTC
Labels: investigation
